"use strict";
const data = JSON.parse(document.getElementById("report-data").textContent);
const $ = id => document.getElementById(id);
// All review/model content is rendered with textContent, never parsed as HTML.
function el(tag, text, cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=String(text);if(cls)node.className=cls;return node;}
function add(parent,...children){children.forEach(child=>parent.appendChild(child));return parent;}
function p(text, cls){return el("p",text,cls);}
function bar(parent,label,value,max,extra="",cls=""){const row=el("div",undefined,"bar-row");const track=el("div",undefined,"track");const fill=el("div",undefined,"fill "+cls);fill.style.width=(max?value/max*100:0)+"%";track.appendChild(fill);add(row,el("span",label),track,el("span",value+extra,"bar-value"));parent.appendChild(row);}
const {manifest:m,stats:s,synthesis:y}=data;
const replyEnabled=m.reply_drafts!==false;
if(!replyEnabled){$("reviews-title").textContent="口コミ一覧";$("reviews-nav").textContent="口コミ一覧";$("reply-note").hidden=true;$("reply-policy").hidden=true;$("search-label").textContent="本文・要約を検索";}
$("place").textContent=m.place_name+"　口コミ分析レポート";
$("headline").textContent="口コミ分析レポート";
$("summary").textContent=y.executive_summary;
$("timestamps").textContent="取得: "+m.collected_at+"　生成: "+data.generated_at;
$("coverage").textContent=m.coverage.full_coverage_verified?"取得件数を照合済み: "+s.count+"件 / 画面の総件数 "+m.coverage.displayed_total+"件。本文分析 "+s.text_count+"件、評価のみ "+s.rating_only_count+"件。":"取得は部分的です: 保存 "+s.count+"件 / 画面の総件数 "+(m.coverage.displayed_total??"不明")+"件。以下は取得した範囲の分析です。";
if(!m.coverage.full_coverage_verified)$("coverage").classList.add("partial");
if(m.coverage.is_sample)$("coverage").prepend(el("strong","架空のサンプルデータです。実店舗の取得・分析結果ではありません。 "));
if(m.coverage.truncated_count)$("coverage").appendChild(p("省略表示が残る本文: "+m.coverage.truncated_count+"件。解釈は暫定です。"));
[[s.mean??"不明","取得分の平均星 / "+s.rating_count+"件"],[s.count,"収集した口コミ"],[s.text_count,"本文を分析"],[s.rating_only_count,"評価のみ"]].forEach(([v,label])=>$("metrics").appendChild(add(el("div",undefined,"metric"),el("strong",v),el("span",label))));
for(let i=5;i>=1;i--)bar($("stars"),i+"つ星",s.stars[i],Math.max(...Object.values(s.stars)),"件");
for(const code of ["positive","negative","mixed","neutral"])bar($("sentiments"),data.sentiments[code],s.sentiments[code],Math.max(...["positive","negative","mixed","neutral"].map(k=>s.sentiments[k])),"件",code);
function evidence(ids){const box=el("div",undefined,"evidence");box.appendChild(el("span","根拠","note"));ids.forEach(id=>{const b=el("button",id);b.type="button";b.addEventListener("click",()=>showReview(id));box.appendChild(b);});return box;}
const topCategories=s.categories.filter(c=>c.mentions).sort((a,b)=>b.mentions-a.mentions);
for(const c of topCategories){const row=el("div",undefined,"category-row");const label=el("button",c.title);label.type="button";label.addEventListener("click",()=>{resetFilters();$("category").value=c.code;updateReviews();$("reviews").scrollIntoView();});const track=el("div",undefined,"track");track.setAttribute("aria-label",c.title+": 肯定"+c.positive+"件、否定"+c.negative+"件、肯否混在"+c.mixed+"件、中立"+c.neutral+"件");for(const code of ["positive","negative","mixed","neutral"]){const part=el("span",undefined,"fill "+code);part.style.width=(c[code]/topCategories[0].mentions*100)+"%";track.appendChild(part);}add(row,label,track,el("small",c.mentions+"件 / "+c.share_text_pct+"%"));$("categories").appendChild(row);}
if(!topCategories.length)$("categories").textContent="本文から話題を特定できる口コミはありません。";
$("high-star").textContent="星4・5でも不満や留保を含む口コミは "+s.high_star_concerns+"件。高評価の本文も改善の材料になります。";
function table(node,headers,rows){const head=el("thead");const tr=el("tr");headers.forEach(h=>tr.appendChild(el("th",h)));head.appendChild(tr);node.appendChild(head);const body=el("tbody");rows.forEach(row=>{const tr=el("tr");row.forEach(cell=>tr.appendChild(el("td",cell)));body.appendChild(tr);});node.appendChild(body);}
table($("cross"),["星","肯定","否定","混在","中立","本文なし"],[5,4,3,2,1].map(i=>[i+"つ星",...["positive","negative","mixed","neutral","unavailable"].map(k=>s.cross[i][k])]));
table($("cohorts"),["画面表記","件数","本文あり","平均星"],s.cohorts.map(c=>[c.label,c.count,c.text_count,c.mean??"—"]));
for(const j of y.journey){const box=add(el("article",undefined,"finding"),el("h4",j.stage),p(j.observation),p("摩擦・確認点: "+j.friction),p("機会: "+j.opportunity),evidence(j.evidence_ids));$("journey").appendChild(box);}
for(const section of ["strengths","concerns","opportunities"]){for(const f of y[section]){const box=el("article",undefined,"finding");add(box,el("h4",f.title),p(f.observation));if(section==="concerns"){const causes=el("div",undefined,"cause-grid");add(causes,add(el("div"),el("b","原因の仮説"),p(f.hypothesis)),add(el("div"),el("b","別の説明"),p(f.alternative)));box.appendChild(causes);box.appendChild(p("確認方法: "+f.verify));}box.appendChild(evidence(f.evidence_ids));$(section).appendChild(box);}if(!y[section].length)$(section).appendChild(p("この取得範囲では、根拠を伴う指摘はありません。","note"));}
for(const a of y.actions){const article=el("article",undefined,"action");const meta=add(el("div",undefined,"action-meta"),el("span","優先度 "+a.priority,"priority"),el("span",a.timeframe),el("span",a.id));const body=add(el("div"),el("h4",a.title),p(a.detail),p("優先する理由: "+a.priority_reason,"note"));const dl=el("dl");[["担当案",a.owner],["工数案",a.effort],["検証指標",a.kpi],["現状値",a.baseline],["目標案",a.target]].forEach(([label,value])=>add(dl,el("dt",label),el("dd",value)));add(body,dl,evidence(a.evidence_ids));add(article,meta,body);$("action-list").appendChild(article);}
$("reply-policy").textContent=y.reply_policy;
for(const [key,title] of Object.entries(data.sentiments)){$("sentiment").appendChild(new Option(title,key));}
for(const [key,title] of Object.entries(data.categories)){$("category").appendChild(new Option(title,key));}
function attention(r){return (r.rating&&r.rating<=2)||r.sentiment==="negative"||r.sentiment==="mixed"||(r.checks.length&&r.sentiment!=="unavailable");}
let limit=25;let matching=[];
function resetFilters(){["search","rating","sentiment","category"].forEach(id=>$(id).value="");$("attention").checked=false;limit=25;}
function review(r){const node=el("details",undefined,"review");node.id="review-"+r.key;const summary=el("summary");add(summary,add(el("div",undefined,"review-meta"),el("span",r.key),el("span",r.rating?"★ "+r.rating:"星不明"),el("span",r.date),el("span",data.sentiments[r.sentiment])),el("div",r.summary_ja));add(node,summary);const tags=el("div",undefined,"tags");r.aspects.forEach(a=>tags.appendChild(el("span",data.categories[a.category]+" / "+data.sentiments[a.polarity],"tag")));add(node,tags,p(r.text||"本文なし。評価の理由は記載されていません。","review-text"));r.aspects.forEach(a=>{const q=el("blockquote");add(q,el("strong",data.categories[a.category]+" / "+data.sentiments[a.polarity]),p(a.quote),p(a.detail,"note"));node.appendChild(q);});if(r.owner_reply)add(node,el("h4","既存の店舗返信"),p(r.owner_reply,"review-text"));if(replyEnabled){const reply=add(el("div",undefined,"reply"),el("strong","返信の下書き / "+r.reply_language),p(r.reply_draft));const copy=el("button","返信案をコピー");copy.type="button";copy.addEventListener("click",async()=>{try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(r.reply_draft);copy.textContent="コピーしました";}catch{const area=el("textarea");area.value=r.reply_draft;area.style.position="fixed";area.style.opacity="0";document.body.appendChild(area);area.select();const done=document.execCommand("copy");area.remove();copy.textContent=done?"コピーしました":"返信文を選択してコピーしてください";}setTimeout(()=>copy.textContent="返信案をコピー",2500);});reply.appendChild(copy);node.appendChild(reply);}if(r.checks.length)node.appendChild(p("確認事項: "+r.checks.join(" / "),"checks"));return node;}
function drawReviews(){const list=$("review-list");list.replaceChildren();matching.slice(0,limit).forEach(r=>list.appendChild(review(r)));$("result-count").textContent="該当 "+matching.length+"件 / 全 "+s.count+"件（表示 "+Math.min(limit,matching.length)+"件）";$("more").hidden=limit>=matching.length;if(!matching.length)list.appendChild(p("条件に合う口コミはありません。検索条件を変更してください。"));}
function updateReviews(){limit=25;const query=$("search").value.trim().toLocaleLowerCase();matching=data.rows.filter(r=>(!query||[r.key,r.text,r.summary_ja,r.reply_draft].join(" ").toLocaleLowerCase().includes(query))&&(!$("rating").value||String(r.rating)===$("rating").value)&&(!$("sentiment").value||r.sentiment===$("sentiment").value)&&(!$("category").value||r.aspects.some(a=>a.category===$("category").value))&&(!$("attention").checked||attention(r)));if($("attention").checked)matching.sort((a,b)=>(a.rating??6)-(b.rating??6));drawReviews();}
function showReview(key){resetFilters();$("search").value=key;updateReviews();const node=$("review-"+key);if(node){node.open=true;node.classList.add("highlight");node.scrollIntoView({block:"start"});}}
["search","rating","sentiment","category","attention"].forEach(id=>$(id).addEventListener(id==="search"?"input":"change",updateReviews));
$("more").addEventListener("click",()=>{limit+=25;drawReviews();});$("print").addEventListener("click",()=>window.print());
$("provenance").textContent=JSON.stringify({店舗:m.place_name,取得日時:m.collected_at,生成日時:data.generated_at,取得元:m.source_url,原文SHA256:m.source_sha256,ツール版:m.tool_version,取得:m.coverage,分析した本文:s.text_count,評価のみ:s.rating_only_count,全行の分類を検証:true},null,2);
updateReviews();
